-- Support for manually registered invoices (historical + external)

-- Allow null customer_id for manual invoices
ALTER TABLE invoices ALTER COLUMN customer_id DROP NOT NULL;

-- Free-text customer name when no customer record exists
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS external_customer_name TEXT;

-- Source: 'system' = generated by MoiAcc, 'manuell' = registered manually
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS kilde TEXT NOT NULL DEFAULT 'system';

-- Ensure either customer_id or external_customer_name is always set
ALTER TABLE invoices ADD CONSTRAINT invoices_kunde_check
  CHECK (customer_id IS NOT NULL OR external_customer_name IS NOT NULL);
